favicon: null
name: kirill
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3042553
  brandStrength: 0.3251677765510976
  lightness: 0.4425532
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.8553191
typography_spectrum: 0.7649205485358834
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5891699038911611
analytics:
  twitter: null
  google: null
  facebook: null
